### ISSUE TITLE
TODO list 待开发列表

### ISSUE THREAD

**Issue by SmallOyster** [SmallOyster/RBAC-CodeIgniter#1]
- [x] **~~引号过滤~~**（貌似ci会防SQL注入）
- [x] 各项管理的编辑页面 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/6ed389e3472878def4d239a6b07f44dc7f5b045e
- [x] 用户个人模块 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/8e5c79e6e4f37636ee93110a6799437cd1b48135 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/c9863bb9cb3bba8436869a39d85432fe19527d24 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ab0e8f54841ac8acabd0489d842e58052d94c58c https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ce1d045f3224bf5f46d780757a6c337dae900c24
- [x] 管理员重置用户密码功能 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/41356946be1e0b9508776015f6be19ad49483e3c https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 操作记录 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/6ed389e3472878def4d239a6b07f44dc7f5b045e https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ce1d045f3224bf5f46d780757a6c337dae900c24
- [x] 给角色分配权限时提前勾选已有权限 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/6ed389e3472878def4d239a6b07f44dc7f5b045e
- [x] 新增菜单 支持 新增“跳出系统”菜单 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ab0e8f54841ac8acabd0489d842e58052d94c58c
- [x] 示例页面（空白页、列表页、信息页）https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 注册后发送邮件验证码 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ca3f3f7dc4555c3638db26ed471a050c11467b5a https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [ ] 代码注释 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 修改系统设置（如系统名称、邮件服务器等） https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ca3f3f7dc4555c3638db26ed471a050c11467b5a
- [x] 修改注册时的默认角色 https://github.com/OysterTech/RBAC-CodeIgniter/commit/ce1d045f3224bf5f46d780757a6c337dae900c24
- [x] 导航栏动态显示时间问候语 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 系统公告功能 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/8e8f420a3c236b278c60bd2e5cfa473d4a828415 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/6af9309de0e57b82325db4a1f3d88595ed3a175c https://github.com/SmallOyster/RBAC-CodeIgniter/commit/fb6e8df6ef830e1256d2aac013267f3bb8ce9e4a https://github.com/SmallOyster/RBAC-CodeIgniter/commit/bc9d2f945e44960484b10901c8edd8844eb47411
- [x] 后台用户管理->状态设置 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 修复https://github.com/SmallOyster/RBAC-CodeIgniter/issues/2 的bug https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 判断是否有权限访问该页面(包括首页，Ajax及其他不在menu数据库表的页面) https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 禁止管理员在用户列表对自己用户进行删除/重置密码操作 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 简化导航栏获取菜单数据的方式 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/5863a36d0951edeef67273c901ad25ff19fc1f76
- [x] 60秒才允许发第二次验证邮件 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/126202dcfa6c220f949862d540b16a11d9b8f309
- [x] 底部显示版权 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/8e8f420a3c236b278c60bd2e5cfa473d4a828415

▲ Last Update: **2018-03-17 15:28**
▲ Last Finish: **2019-03-17 22:17**

**Comment by SmallOyster** [comment]
- [x] 通知列表 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/8e8f420a3c236b278c60bd2e5cfa473d4a828415

▲ Last Update: **2018-07-17 11:59**
▲ Last Finish: **2019-03-17 22:18**

**Comment by SmallOyster** [comment]
- [x] 全面将ID改回为Id（更符合正规的驼峰法）https://github.com/SmallOyster/RBAC-CodeIgniter/commit/a4e74bc95a239b3f92943d4aa8b714c80706f0d3
- [x] 全面适配AdminLTE UI框架
- [x] 支持多角色 https://github.com/SmallOyster/RBAC-CodeIgniter/commit/ae92b53e1c558d0fa66f5052b40104c0758b8f18
- [x] ~~通知内容的引号转义~~
- [x] 菜单管理改回用zTree https://github.com/SmallOyster/RBAC-CodeIgniter/commit/4d7df44b0cb08eb1ba2fca324d1b594ab6a24691
- [x] 大范围使用Vue.js

▲ Last Update: **2019-05-26 09:51**
▲ Last Finish: **2019-05-18 21:38**
